stages:
  - stage

deploy:
  tags:
    - ained
  stage: stage
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t automatedtestingservice/uva-tester:latest .
    - docker push automatedtestingservice/uva-tester:latest
    - |
      curl -X POST "https://cs.ttu.ee/services/arete/api/v2/course/uva-tester" -H "accept: */*" -H "X-Docker-Token: uva-tester $ARETE_TOKEN"
  only:
    - master
